#!/usr/bin/python3.5
print ("Hello World!")
print ("Hello Again")
print ("I like typing this .")
print ("This is fun.")
print ("Yey! Printing.")
print ("I'd much rather you not'.")
print ('I "Said " do not touch this.')
print ("cats = 100.00")
print ("Hey %s  there .” % "you")